# MySQL.  Versions 4.1 and 5.0 are recommended.
# 
# Install the MYSQL driver
#   gem install mysql2
#
# Ensure the MySQL gem is defined in your Gemfile
#   gem 'mysql2'
#
# And be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html
development:
  adapter: postgresql
  encoding: unicode
  database: isopt_development
  pool: 5
  username: WonyoungSo
  host: localhost
  password:

# test:
#   adapter: postgresql
#   encoding: unicode
#   host: localhost
#   database: wonyoungso_test
#   pool: 5
#   username: postgres
#   password:

# production:
#   adapter: postgresql
#   encoding: unicode
#   host: localhost
#   database: wonyoungso_production
#   pool: 5
#   username: postgres
#   password: yourse1234f